[package]
name = "dotacord"
edition = "2021"

[dependencies]
poise = { path = "../ext/poise", features = ["cache"] }
# poise = { git = "https://github.com/serenity-rs/poise", rev = "fe2f25097166e1e7fb56f341cbad9a2bc771a931"}
serenity = { git = "https://github.com/serenity-rs/serenity", rev = "3009d22082cadab93e0f463e9d9868b656cd62bc" }

tokio = { version = "1", features = ["macros", "rt-multi-thread", "fs"] }
sqlx = { version = "0.7", default-features = false, features = ["runtime-tokio", "sqlite", "macros"] }
serde_json = "1.0.145"
rand = "0.9.2"
serde = { version = "1", features = ["derive"] }
toml = "0.7"
tracing-subscriber = { version = "0.3.19", features = ["env-filter", "json", "local-time"] }
tracing = "0.1"
chrono = "0.4.42"
reqwest = { version = "0.12.23", features = ["json"] }
clap = { version = "4", features = ["derive"] }
ureq = "2.12"

[workspace.lints.rust]
unused = "deny"

