database_path = "~/db/dotacord/dotacord.db"
heroes_path = "~/db/dotacord/heroes.json"
api_key_var = "KEY_DOTACORD"

online_status = "online"

max_message_length = 1900

max_players_per_server = 5
roll_countdown_duration_sec = 3
flip_countdown_duration_sec = 5
countdown_offset_ms = 50

[cooldowns]
user_refresh_min = 15
admin_refresh_min = 15

[scheduler]
enabled = true
heartbeat_interval_minutes = 3
timer_check_mins = 1

[scheduler.auto_reload]
enabled = true
start_hour = 18
end_hour = 2
interval_minutes = 60

[scheduler.weekly_leaderboard]
enabled = true
minute = 0

[scheduler.monthly_leaderboard]
enabled = true
minute = 0

[log]
level = "info"
path = "~/logs/dotacord.log"
json_path = "~/logs/dotacord.json.log"
seq_endpoint = "http://localhost:5341/api/events/raw"

