database_path = "D:/dev/rust/dotacord/data/dotacord.db"
heroes_path = "D:/dev/rust/dotacord/data/heroes.json"
api_key_var = "key:dotacord"

# Log level: trace, debug, info, warn, error
log_level = "info"

log_path = "D:/dev/rust/dotacord/data/dotacord.log"
log_json_path = "D:/dev/rust/dotacord/data/dotacord.json.log"
seq_endpoint = "http://localhost:5341/api/events/raw"

# Example: register application commands to a single guild for faster testing
# test_guild = 927307976497315930
# test_guild = 927307976497315930
test_channel = 927307976497315930

online_status = "online"
# online_status = "invisible"

max_message_length = 1900

max_players_per_server = 5
clear_commands_on_startup = false
countdown_duration_ms = 10000
countdown_offset_ms = 100

[scheduler]
enabled = true
heartbeat_interval_minutes = 1
timer_check_mins = 1
auto_reload_start_hour = 16
auto_reload_end_hour = 3
auto_reload_interval_minutes = 60
weekly_leaderboard_day = 7
weekly_leaderboard_hour = 21
monthly_leaderboard_day = 1
monthly_leaderboard_hour = 18
