database_path = "~/dev/rust/dotacord/data/dotacord.db"
heroes_path = "~/dev/rust/dotacord/data/heroes.json"
api_key_var = "KEY_DOTACORD"

# Log level: trace, debug, info, warn, error
log_level = "info"

log_path = "~/dev/rust/dotacord/data/dotacord.log"
log_json_path = "~/dev/rust/dotacord/data/dotacord.json.log"
seq_endpoint = "http://localhost:5341/api/events/raw"

# Example: register application commands to a single guild for faster testing
# test_guild = 927307976497315930

# Testing Server
# test_guild = 1246056760641585242
# test_channel = 1414209805308133539

# online_status = "online"
online_status = "invisible"

max_message_length = 1900

max_players_per_server = 5
roll_countdown_duration_sec = 3
flip_countdown_duration_sec = 5
countdown_offset_ms = 50

[cooldowns]
user_refresh_min = 15
admin_refresh_min = 15

[scheduler]
enabled = true
heartbeat_interval_minutes = 3
timer_check_mins = 1

[scheduler.auto_reload]
enabled = true
start_hour = 15
end_hour = 23
interval_minutes = 3

[scheduler.weekly_leaderboard]
enabled = true
minute = 31

[scheduler.monthly_leaderboard]
enabled = true
minute = 31

